### PR TITLE
Qr solve fix

### PR DESCRIPTION
**Pull request by JensWehner**
Restructured qr_solve_constrained a bit
removed unnecssary minus sign
added unit test

this breaks CSG a bit, see pull request in CSG

### CODE REVIEW

**Comment by junghans** [comment]
@schererc: Can you please check that this cleanup doesn't alter your `csg_fmatch` results?

**Comment by JensWehner** [comment]
Before it did not give x but -x as the solution.

**Comment by junghans** [comment]
@JensWehner might a force vs dV/dr thing.

**Comment by junghans** [comment]
Oh well, I meant test in combination with votca/csg#248.

**Comment by JensWehner** [comment]
@junghans Good point, but I think it is not because there were a couple of comments in the code, saying ` b = -y; // why is it -y?`
and
`// TODO: here i changed the sign, check again! (victor)\
x = -prec_prod( Q, x );`

**Comment by junghans** [comment]
I think, you removed one minus in tools and one in csg, so we should be good.

**Pull request merged**
