### PR TITLE
include also sparse part of the library

### PR DESCRIPTION
**Pull request by JensWehner**
for usage in xtp

### CODE REVIEW

**Comment by JensWehner** [comment]
Ohh in tools the master branch is not protected?

**Comment by junghans** [comment]
@JensWehner it is not protected for admins!

**Comment by JoshuaSBrown** [comment]
@junghans how come you always use **!** instead of **.** at the end of your sentences you know that is near equivalent to yelling right? :)

**Comment by junghans** [comment]
This update is part of https://github.com/votca/votca/pull/126.

**Comment by junghans** [comment]
> @junghans how come you always use **!** instead of **.** at the end of your sentences you know that is near equivalent to yelling right? :)

Fixed ;-)

**Comment by JensWehner** [comment]
ohh.....finally... :D

**Comment by JoshuaSBrown** [comment]
Hahaha!!!!!!

**Pull request merged**
