### PR TITLE
[WIP] Clean namespace from using

### PR DESCRIPTION
**Pull request by JoshuaSBrown**

### CODE REVIEW

**Comment by JensWehner** [comment]
I think we should merge into stable not master, atm. @junghans

**Comment by JoshuaSBrown** [comment]
@junghans ?

**Comment by junghans** [comment]
Is that PR something we need right now to fix the memory leaks? Or can we wait with merging this?

**Comment by JoshuaSBrown** [comment]
No this is not a memory leak problem. It is technical debt, which is why I picked master.

**Comment by junghans** [comment]
Ok, it seems to breaks the code in master of ctp.

**Comment by JensWehner** [comment]
@JoshuaSBrown @junghans This can be closed, as all using namespace were removed already.

**Comment by junghans** [comment]
Ok

**Pull request closed without merging**
