### PR TITLE
FindMKL.cmake: fix target creation

### PR DESCRIPTION
**Pull request by junghans**
For votca/votca#246

### CODE REVIEW

**Comment by junghans** [comment]
No wait, MKL::Core always gets created, so I need to fix that too

**Comment by baumeier** [comment]
`cd /home/bbaumeie/work/votca/build/tools/src/libtools && /usr/bin/c++  -Dvotca_tools_EXPORTS -I/home/bbaumeie/work/votca/build/tools/src/libtools -I/home/bbaumeie/work/votca/tools/include -I/home/bbaumeie/work/votca/build/tools/include -isystem /usr/include/eigen3 -isystem /opt/intel/mkl/include -isystem /opt/intel/mkl/include/fftw  -Wall -Wextra -Wpedantic -Wshadow -Wconversion -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/votca_tools.dir/version.cc.o -c /home/bbaumeie/work/votca/tools/src/libtools/version.cc
make[2]: *** No rule to make target 'MKL_ThreadingLibrary_LINK_LIBRARY-NOTFOUND', needed by 'tools/src/libtools/libvotca_tools.so.7'.  Stop.
make[2]: Leaving directory '/home/bbaumeie/work/votca/build'
`

with votca/votca#246

**Comment by junghans** [comment]
Hmm, does it work with `-DMKL_THREAD_LAYER="Intel OpenMP"` ?

**Comment by baumeier** [comment]
now seems to work with votca/votca#246

**Pull request merged**
