### PR TITLE
Fix name from beadmass inference

### PR DESCRIPTION
**Pull request by JensWehner**

### CODE REVIEW

**Comment by JensWehner** [comment]
@votca-bot changelog: changed tolerance for getting element names from mass

**Comment by junghans** [comment]
Shouldn't that go into stable instead?

**Comment by JensWehner** [comment]
I do not think it can go into stable because I also have to change CSG.

**Comment by junghans** [comment]
> I do not think it can go into stable because I also have to change CSG.

Why not both?

**Comment by JensWehner** [comment]
good point

**Review by junghans — APPROVED** [review]

**Pull request merged**
