### PR TITLE
Update compare function for floats

### PR DESCRIPTION
**Pull request by JensWehner**

### CODE REVIEW

**Comment by junghans** [comment]
```
The following tests FAILED:
	 41 - integration_Compare_csg_reupdate_output (Failed)
	 43 - integration_Compare_csg_fmatch_output (Failed)
	 45 - integration_Compare_csg_fmatch_3body_output1 (Failed)
	 46 - integration_Compare_csg_fmatch_3body_output2 (Failed)
	 47 - integration_Compare_csg_fmatch_3body_output3 (Failed)
	 49 - integration_Compare_csg_map_output (Failed)
	 51 - integration_Compare_csg_stat_output1 (Failed)
	 52 - integration_Compare_csg_stat_output2 (Failed)
	 54 - integration_Compare_csg_stat_angular_output (Failed)
	 56 - integration_Compare_csg_stat-imc_output (Failed)
	 57 - integration_Compare_csg_stat-imc_output_2 (Failed)
	 59 - integration_Compare_csg_resample_akima_output (Failed)
	 61 - integration_Compare_csg_resample_cubic_output (Failed)
	 63 - integration_Compare_csg_resample_linear_output (Failed)
	 65 - integration_Compare_csg_resample_cubicfit_output (Failed)
```

**Comment by JensWehner** [comment]
We have two problems:

a) the new comparison is stricter than the old one

b) we also compare the errors to a ref error of 0. 

example: 
ref_file:
#value # error
1300 0
50 0
2 0

result_file:
#value # error
1300 1e-3
50 1e-5
2 1e-6

the relative errors for the results are compareable but the absolute error for 1300 is too big because it is larger than the threshold 

The first problem is easily solved by changing the threshold parameter, the second I do not know.

**Comment by junghans** [comment]
Could we use the same comparison as here:
https://github.com/votca/csg/blob/master/share/scripts/inverse/functions_common.sh#L745
i.e.:
```
if (x==y){
  return equal;
}else{
  if (abs(x-y)<error){
    return equal;
  }else{ 
    return ( abs(x-y)/max(abs(x),abs(y)) < e );
  }
}
```

**Comment by JensWehner** [comment]
my commit an that should be the same, I think

**Comment by JensWehner** [comment]
I check it tomorrow with more care.

**Comment by junghans** [comment]
Ping @JensWehner

**Comment by JensWehner** [comment]
yeah I know. The situation has not changed.

**Comment by junghans** [comment]
@JoshuaSBrown please review.

**Comment by JensWehner** [comment]
@junghans thanks for fixing this finally.

**Pull request merged**
