### PR TITLE
Set a default value for the number of bins to 100, it was being used …

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
…without being initialized

### CODE REVIEW

**Comment by JoshuaSBrown** [comment]
Your saying the constructor takes a parameter that you must provide to initialize it?

**Comment by JensWehner** [comment]
no , 
you can write 

`int _size=0;`

in the private section and than you have to do nothing in the constructor

**Comment by JoshuaSBrown** [comment]
Ok, so moving initialization to the header file in the private section and setting it to a default of 0 instead of 100?

**Comment by JensWehner** [comment]
I am working on something like it atm.

**Comment by JensWehner** [comment]
100 is a good number

**Comment by JoshuaSBrown** [comment]
Ok, I've assigned you to the merge, so I don't do anything else.

**Pull request closed without merging**
