### PR TITLE
cmake: inject --no-as-needed for mkl + gcc

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
@baumeier does this fix your issue?

**Comment by baumeier** [comment]
@junghans when I use votca/votca, the new flags don't seem to end up in the CMakeCache.txt

**Comment by junghans** [comment]
It won't as it isn't added to the cache. It should show up in the linking though, check with `make VERBOSE=1`

**Comment by baumeier** [comment]
I made a clean install according to votca/votca instructions (and checking out master in tools). Still running into:

` [71%] Building CXX object xtp/src/tools/CMakeFiles/xtp_tools.dir/xtp_tools.cc.o
cd /home/bbaumeie/work/votca/build/xtp/src/tools && /usr/bin/c++  -DBOOST_UBLAS_NDEBUG -I/home/bbaumeie/work/votca/xtp/include -I/usr/include/hdf5/serial -I/home/bbaumeie/work/votca/build/xtp/include -I/home/bbaumeie/work/votca/csg/include -I/home/bbaumeie/work/votca/tools/include -I/home/bbaumeie/work/votca/build/tools/include -isystem /usr/include/eigen3 -isystem /opt/intel/mkl/include -isystem /opt/intel/mkl/include/fftw  -Wall -Wextra -Wpedantic -Wshadow -Wconversion -fopenmp -O3 -DNDEBUG   -std=c++14 -o CMakeFiles/xtp_tools.dir/xtp_tools.cc.o -c /home/bbaumeie/work/votca/xtp/src/tools/xtp_tools.cc
[ 71%] Linking CXX executable xtp_tools
cd /home/bbaumeie/work/votca/build/xtp/src/tools && /usr/bin/cmake -E cmake_link_script CMakeFiles/xtp_tools.dir/link.txt --verbose=1
/usr/bin/c++   -Wall -Wextra -Wpedantic -Wshadow -Wconversion -fopenmp -O3 -DNDEBUG   CMakeFiles/xtp_tools.dir/xtp_tools.cc.o  -o xtp_tools -Wl,-rpath,/home/bbaumeie/work/votca/build/xtp/src/libxtp:/home/bbaumeie/work/votca/build/csg/src/libcsg:/home/bbaumeie/work/votca/build/tools/src/libtools:/usr/lib/x86_64-linux-gnu/hdf5/serial: ../libxtp/libvotca_xtp.so.7 ../../../csg/src/libcsg/libvotca_csg.so.7 ../../../tools/src/libtools/libvotca_tools.so.7 /usr/lib/x86_64-linux-gnu/libboost_program_options.so -lmkl_core -lmkl_intel_lp64 -lmkl_intel_thread -liomp5 -ldl /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so -lpthread /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.so -lm 
/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined reference to `mkl_sparse_d_csr__g_n_syrkd_f_ker_i4'
/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined reference to `mkl_sparse_c_dense_u_sv8x8_i8'
/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined reference to `mkl_cpds_lp64_sp_cpds_slv_bwd_update_nrhs_real'
/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined reference to `mkl_spblas_zdia1ttluf__smout_par'
/opt/intel/compilers_and_libraries_2019.5.281/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so: undefined reference to `mkl_pds_lp64_pds_sym_indef_diag_bwd_ker_seq_nrhs_real'
`

**Comment by junghans** [comment]
Ok, I think we need to do this on the `votca/votca` level then.

**Comment by junghans** [comment]
Try https://github.com/votca/votca/pull/246 instead

**Pull request merged**
