### PR TITLE
doc: make programs as subsections

### PR DESCRIPTION
**Pull request by junghans**
Improvement of https://www.votca.org/tools/reference.html

@JensWehner, should every program have its own html page instead of list all 3 tools in one page?

### CODE REVIEW

**Comment by JensWehner** [comment]
Good idea. I like this

**Review by JensWehner — APPROVED** [review]

**Comment by junghans** [comment]
@jens, this isn't one page per-program yet, this PR just add headers.

If we want to do separate pages, we will need to reorg a bit more.

The problem is that the `votca_help2doc` generated pages doesn't include a header, hence sphinx will pick up the first section, i.e. `NAME`, for each page when adding the page with in `..toctree` instead of using `..include`.

**Comment by JensWehner** [comment]
So we would have to automatically generate the headers as well? In that case I think it is better to leave them in one file.

**Comment by junghans** [comment]
> So we would have to automatically generate the headers as well? In that case I think it is better to leave them in one file.

We could do that with `votca_help2doc` automatically.

Or create a simple rst file like:
```
PROGRAM
^^^^^^^^^^

..include PROGRAM.rst
```
for each executable.

**Review by felipeZ — APPROVED** [review]
LGTM

**Comment by JensWehner** [comment]
@junghans I do not really care either way, I prefer the more maintainable solution.

**Comment by junghans** [comment]
> @junghans I do not really care either way, I prefer the more maintainable solution.

Then this will the solution for now ;-)

**Pull request merged**
