### PR TITLE
property can now convert to some eigen structures

### PR DESCRIPTION
**Pull request by JensWehner**
-Property can now directly convert to Eigen::Vector3d and Eigen::VectorXd

I tried to get a more general implementation but as far as I know I cannot partially specialize the templated function

### CODE REVIEW

**Comment by junghans** [comment]
And how about a test?

**Comment by JensWehner** [comment]
Good idea, there is actually a big problem with this commit.

**Comment by JensWehner** [comment]
Or at least I think so. We have big problem compiling with mkl now, because CTP uses cblas from GSL and then both versions get confused, with each other.

**Comment by JensWehner** [comment]
the intel blas and the gsl blas

**Pull request merged**
