### PR TITLE
CI: add mkl builds

### PR DESCRIPTION
**Pull request by junghans**

### CODE REVIEW

**Comment by junghans** [comment]
Hmm clang + mkl seems to be broken!

**Comment by JensWehner** [comment]
What do you mean?

**Comment by junghans** [comment]
> What do you mean?

See https://github.com/votca/tools/runs/824046380?check_suite_focus=true
```
2020-06-30T21:02:41.2668429Z   9/193 Test   #9: memory_test_crosscorrelate .........................***Failed    2.44 sec
2020-06-30T21:02:41.2680585Z ==11438== Memcheck, a memory error detector
2020-06-30T21:02:41.2681306Z ==11438== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
2020-06-30T21:02:41.2681587Z ==11438== Using Valgrind-3.16.0 and LibVEX; rerun with -h for copyright info
2020-06-30T21:02:41.2681718Z ==11438== Command: /__w/tools/tools/builddir/tools/src/tests/unit_test_crosscorrelate
```

**Comment by junghans** [comment]
@JensWehner ok with same problem with gcc, so you will have to fix that first.

**Comment by junghans** [comment]
@JoshuaSBrown the failure is in a valgin test, can you have a look?

**Comment by JensWehner** [comment]
mkl does not like valgrind and vice versa

https://stackoverflow.com/questions/36197527/insight-as-to-why-valgrind-shows-memory-leak-for-intels-mkl-lapacke

**Comment by junghans** [comment]
The actual valgrind error is:
```
Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Pull request merged**
