### PR TITLE
link against MKL:RT to support pyxtp

### PR DESCRIPTION
**Pull request by junghans**
for https://github.com/votca/xtp/pull/673

### CODE REVIEW

**Comment by junghans** [comment]
@JensWehner can you make sure this has no performance implications?

**Review by JensWehner — APPROVED** [review]

**Review by JensWehner — CHANGES_REQUESTED** [review]
Sorry, what do you mean? In regards to what, what is mkl_rt?

**Comment by JensWehner** [comment]
THis might completely mess with our threading model I will experiment a bit.

**Comment by junghans** [comment]
@jens read https://groups.google.com/g/kaldi-help/c/m3nyQke0HS0/m/4fj8gkSWAgAJ for details why we need to switch for dynamically loaded object e.g. python modules.

**Comment by jens** [comment]
Wrong jens...

**Comment by JensWehner** [comment]
@junghans I looked at the description and it makes sense. I will test it on the weekend.

**Comment by junghans** [comment]
> Wrong jens...

Sorry!

**Comment by junghans** [comment]
Oh man...
```
2021-02-10T14:18:52.8430614Z The following tests FAILED:
2021-02-10T14:18:52.8431905Z 	 21 - integration_Run_csg_fmatch (SEGFAULT)
2021-02-10T14:18:52.8432900Z 	 22 - integration_Compare_csg_fmatch_output (Failed)
2021-02-10T14:18:52.8433888Z 	 23 - integration_Run_csg_fmatch_3body (SEGFAULT)
2021-02-10T14:18:52.8435109Z 	 24 - integration_Compare_csg_fmatch_3body_output1 (Failed)
2021-02-10T14:18:52.8439061Z make[3]: *** [Makefile:137: test] Error 8
2021-02-10T14:18:52.8439884Z 	 25 - integration_Compare_csg_fmatch_3body_output2 (Failed)
2021-02-10T14:18:52.8440899Z 	 26 - integration_Compare_csg_fmatch_3body_output3 (Failed)
2021-02-10T14:18:52.8443859Z 	 42 - integration_Compare_csg_imc_solve_output (Failed)
2021-02-10T14:18:52.8445150Z 	 44 - integration_Compare_csg_imc_solve_reg_output_2 (Failed)
2021-02-10T14:18:52.8446404Z 	 45 - integration_Compare_csg_imc_solve_reg_output_3 (Failed)
2021-02-10T14:18:52.8447689Z 	 46 - integration_Compare_csg_imc_solve_reg_output_4 (Failed)
```

it seems the change in mkl makes `csg_fmatch` segfault and `csg_imc_solve` change the results! mkl for the win!

**Comment by JensWehner** [comment]
hmmm.. partial success.

**Comment by junghans** [comment]
ping @JensWehner

**Comment by JensWehner** [comment]
Unfortunately, I still do not have a good idea.

**Comment by JensWehner** [comment]
So I looked into it and all tests pass if I set the number of OpenMP threads to 1. 

So there is at least a problem with openmp. 
It also seems that gcc and mkl can work with iopenmp acccording to
https://stackoverflow.com/questions/25986091/telling-gcc-to-not-link-libgomp-so-it-links-libiomp5-instead

so we should always use iopenmp with mkl, as we did before. 
The mkl_rt failing tests are a problem with the openmp scheduling

**Comment by JensWehner** [comment]
clangs default library seems to be iopenmp as well. So the old openmp solution with always using iopenmp when mkl is found was correct.

**Comment by junghans** [comment]
Replaced by https://github.com/votca/votca/pull/767

**Pull request closed without merging**
