### PR TITLE
removed random class

### PR DESCRIPTION
**Pull request by JensWehner**
removed the random class 
as the random2 class exists and is used everywhere.

### CODE REVIEW

**Comment by junghans** [comment]
I think it would be good to switch `Random2`to Mersenne Twister, which comes with C++11.

**Comment by JensWehner** [comment]
I did some research on the issue and that is not a good idea. The algorithm currently implemented in tools is a lot faster than Mersenne Twister, whilst giving approximately the same quality of randomness.

**Comment by JensWehner** [comment]
A also did a benchmark on it and at east the speed part is true.

**Comment by junghans** [comment]
Most important question, is it implemented correctly?

**Comment by JensWehner** [comment]
I do not know.

**Pull request merged**
