### PR TITLE
Added tests for unitconverter

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
Class for helping the io readers in csg convert between different units.

### CODE REVIEW

**Comment by JensWehner** [comment]
why do we make it functions and not constexpr or even templated, I mean the stuff is known at compile time. Otherwise not bad, I thought I remember something similar in tools somewhere

**Comment by JoshuaSBrown** [comment]
I guess I could just return the ratio and not the value into the functions, then I could make it a constexpr. The only thing in tools I see is the constants file, but this is not flexible enough. If I just used the values in constants file it would simply be a hard coded value. If I pass in enums based on the types being used I can at least update the ratio based on the types. E.g. if I'm using your Atom container vs the csg molecule type, if each of the containers has a typedef associated with the units it is using I can simply pass that to the input or output reader during compile time. 

E.g. 

    class AtomContainer {
       typedef tools::DistanceUnit::ang distance_units_;
    };

    class Molecule {
        typedef tools::DistanceUnit::nanometer distance_units_;
    };

    /// Assuming default units are nm in the pdbreader
    PDBReader {
         typedef tools::DistanceUnit::nanometer distance_unit_;
         template<class T> 
         void Read(T & container){
             :
             double x_pos << file_identifier;
             Converter converter;
             double x_pos_correct_units = converter.convert(distance_unit_,T::distance_unit_) * x_pos;
             :
                           
         }
    };

**Comment by JensWehner** [comment]
`double x_pos_correct_units = converter.convert<distance_unit_,T::distance_unit_>()*x

**Comment by JensWehner** [comment]
otherwise it is a great idea, which could solve all unit problems. That is why I am commenting..

**Comment by JoshuaSBrown** [comment]
Hmm, how would you enforce that the compatible enums are passed in. Template specialization? 

E.g. Preventing the following which does not make sense:

    convert<distance_unit_,T::time_unit_>();

**Comment by JensWehner** [comment]
Ohh good point, your way we would get a compile error because no overload an be found, or not?

We do a std::enable_if(std::same(INPUT,length)) or so i am not sure it works fully yet

**Comment by JoshuaSBrown** [comment]
@JensWehner So I made some changes to make it run at compile time, if you don't have any issues, I'll just merge this how it is.

**Pull request merged**
