### PR TITLE
changed long int to Eigen::Index

### PR DESCRIPTION
**Pull request by JensWehner**
Related to https://github.com/votca/xtp/issues/339

### CODE REVIEW

**Comment by junghans** [comment]
Fails on i585:
```
[   97s] [ 10%] Building CXX object src/libtools/CMakeFiles/votca_tools.dir/edge.cc.o
[   97s] cd /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/build/src/libtools && /usr/bin/c++  -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -Dvotca_tools_EXPORTS -I/home/abuild/rpmbuild/BUILD/tools-1.6_rc1/build/src/libtools -I/home/abuild/rpmbuild/BUILD/tools-1.6_rc1/include -I/home/abuild/rpmbuild/BUILD/tools-1.6_rc1/build/include -isystem /usr/include/eigen3  -fomit-frame-pointer -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -DNDEBUG -O2 -g -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/votca_tools.dir/edge.cc.o -c /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/src/libtools/edge.cc
[   97s] /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/src/libtools/edge.cc:34:6: error: no declaration matches 'long int votca::tools::Edge::getOtherEndPoint(votca::Index) const'
[   97s]    34 | long Edge::getOtherEndPoint(Index ver) const {
[   97s]       |      ^~~~
[   97s] In file included from /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/src/libtools/edge.cc:23:
[   97s] /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/include/votca/tools/edge.h:51:9: note: candidate is: 'votca::Index votca::tools::Edge::getOtherEndPoint(votca::Index) const'
[   97s]    51 |   Index getOtherEndPoint(Index ver) const;
[   97s]       |         ^~~~~~~~~~~~~~~~
[   97s] /home/abuild/rpmbuild/BUILD/tools-1.6_rc1/include/votca/tools/edge.h:40:7: note: 'class votca::tools::Edge' defined here
[   97s]    40 | class Edge {
[   97s]       |       ^~~~
[   97s] make[2]: *** [src/libtools/CMakeFiles/votca_tools.dir/build.make:170: src/libtools/CMakeFiles/votca_tools.dir/edge.cc.o] Error 1
[   97s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/tools-1.6_rc1/build'
[   97s] make[2]: *** Waiting for unfinished jobs....
```

**Comment by junghans** [comment]
Let's see if that helps.

**Comment by JensWehner** [comment]
there is like 30 occurences of `long` in the code atm

**Comment by JensWehner** [comment]
PRs coming up.

**Comment by junghans** [comment]
Now it seems to build at least....

**Comment by JensWehner** [comment]
so we are good?

**Comment by junghans** [comment]
Still running, give me a sec.

**Pull request merged**
