### PR TITLE
Added parameters class

### PR DESCRIPTION
**Pull request by JoshuaSBrown**
Description has been added to the parameters.h class file. Essentially establishes a standardized method for initializing class constructors.

### CODE REVIEW

**Comment by JensWehner** [comment]
can you describe a bit more what the PR is about?

**Comment by JoshuaSBrown** [comment]
@JensWehner Take a look now.

**Comment by JensWehner** [comment]
For me the name is confusing, a bit to generic, could we call it particle_parameter or so, because I think it would be a bad idea if someone uses it outside of file readers and writers

**Comment by JensWehner** [comment]
Otherwise I like it

**Comment by JoshuaSBrown** [comment]
How about topology Parameter because it can be used with segments molecules etc...?

**Comment by JensWehner** [comment]
structure_parameter? otherwise topology_parameter is fine

**Pull request merged**
